services:
  db:
    image: postgres
    volumes:
      - ${REGLIST_DB:-./tmp/db}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: rails server -b 0.0.0.0
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    image: reglist-web
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db