FROM reglist-web:latest AS app

WORKDIR /app

COPY . /app

RUN bundle exec rake assets:precompile

COPY bin/entrypoint-prod.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE  3000

CMD ["rails", "server", "-b", "0.0.0.0"]
