---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.4-node
        environment:
          PGHOST: localhost
          PGUSER: reglist
          RAILS_ENV: test
      - image: cimg/postgres:14.7
        environment:
          POSTGRES_USER: reglist
          POSTGRES_DB: reglist_test
          POSTGRES_PASSWORD: ""
    working_directory: ~/reglist
    steps:
      - checkout

      - restore_cache:
          name: Restore bundle cache
          key: reglist-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run:
          name: Set local bundle path
          command: bundle config set --local path 'vendor/bundle'
      - run:
          name: Bundle install
          command: bundle install

      - save_cache:
          name: Store bundle cache
          key: reglist-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Wait for DB
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Run the tests
      - run:
          name: Run tests
          command: bundle exec rake